"""Add description into Postion table

Revision ID: 46e50fd51755
Revises: c9c5b709566a
Create Date: 2024-03-28 19:41:10.111071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e50fd51755'
down_revision: Union[str, None] = 'c9c5b709566a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('potion', sa.Column('description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('potion', 'description')
    # ### end Alembic commands ###
